<a href="https://colab.research.google.com/github/thekkethilsreeraj/ML-with-Python/blob/main/Python_Assignment_Online_Retail_Sales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:

path_2_train_file = '/content/drive/MyDrive/assignment_new_2020/assignment_new_2020/train.csv'
df = pd.read_csv(path_2_train_file)

In [4]:
df.shape

(1999999, 332)

In [5]:
colnames=df.columns

In [6]:
import pandas
import random

n = 1999999 #number of records in file
s = 20000 #desired sample size
filename = path_2_train_file
skip = sorted(random.sample(range(n),n-s))
df_sample = pandas.read_csv(filename, skiprows=skip)

In [7]:
df_sample.shape

(20000, 332)

In [8]:
df_sample.columns=colnames

In [9]:
df_sample.head()

   day  user_id  item_id  col2    col3  ...  col326  col327  col328  col329  label
0  466   712361  7538266   0.0  0.1537  ...       0       1       0       0      0
1  466  1506127  7523547   0.0  0.1920  ...       0       1       0       0      0
2  466   134054  7538264   0.0  0.2733  ...       0       1       0       0      0
3  466   127243  7523619   0.0  0.3632  ...       0       1       0       0      0
4  466  1765550  7538283   0.0  0.4160  ...       0       1       0       0      0

[5 rows x 332 columns]

In [10]:
del df

In [11]:

df_sample['item_id'].value_counts()

7976405    133
7538250    110
7594057    108
7538266     98
7538289     97
          ...
7977007      1
8081426      1
8009713      1
7978960      1
7897088      1
Name: item_id, Length: 1762, dtype: int64

In [12]:


df_sample['user_id'].value_counts()

6588529    26
4368251    24
9134133    22
2490654    20
39865      18
           ..
3806715     1
4549676     1
6348274     1
277998      1
118834      1
Name: user_id, Length: 13874, dtype: int64

In [13]:
label = df_sample['label'].values

In [14]:
data = df_sample.drop(columns=['label','day','item_id','user_id']).values

In [15]:
X = data.copy()
y = np.array(label.copy())
y[:5]

array([0, 0, 0, 0, 0])

In [16]:
y = (y > 0)*1
nb_class = len(set(y))
print(nb_class)
id_Train = np.array([None]*nb_class)
id_Test = np.array([None]*nb_class)
for i in range(nb_class):
    id_i = np.where(y==i)[0]
    id_i_train, id_i_test = train_test_split(id_i, test_size=0.2)
    id_Train[i] = id_i_train
    id_Test[i] = id_i_test

id_Train = np.concatenate(id_Train)
id_Test = np.concatenate(id_Test)

X_train = X[id_Train]
Y_train = y[id_Train]
X_test = X[id_Test]
Y_test = y[id_Test]

2

In [17]:
X_train[0]

array([0.    , 0.2706, 0.    , 0.1707, 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.1707, 0.4413, 0.    , 0.    , 0.    ,
       0.2706, 0.    , 0.    , 0.    , 0.3964, 0.    , 0.5411, 0.    ,
       0.    , 0.1707, 0.1707, 0.1707, 0.    , 0.    , 0.    , 0.    ,
       0.3414, 0.    , 0.    , 0.6317, 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.2706, 0.    , 0.    , 0.    , 0.1707,
       0.2706, 0.2706, 0.    , 0.    , 0.1707, 0.3964, 0.1707, 0.    ,
       0.    , 0.3414, 0.    , 0.    , 0.    , 0.    , 0.    , 1.    ,
       1.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 1.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 1.    , 0.    , 0.5058, 0.    , 0.4787,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.1596,
       0.448 , 0.    , 0.    , 0.    , 0.    , 0.    , 0.1596, 0.1596,
       0.    , 0.    , 0.3705, 0.    , 0.1596, 0.2529, 0.1596, 0.    ,
       0.    , 0.    , 0.1596, 0.    , 0.4125, 0.4125, 0.    , 0.5905,
       0.    , 0.1596, 0.    , 0.    , 0.    , 0.    , 0.    , 0.3705,
       0.    , 0.    , 0.    , 0.    , 0.448 , 0.3191, 0.    , 0.    ,
       0.    , 0.    , 0.2529, 0.    , 0.1596, 0.3705, 1.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 1.    , 0.    , 0.    ])

In [18]:
id_toTrain = np.array([np.where(Y_train==i)[0] for i in range(nb_class)])

size_max = [len(id_toTrain[i]) for i in range(nb_class)]
print("before resampling")
print(size_max)

blc = 150
for i in range(len(size_max)):
    if size_max[i] > blc:
        size_max[i] = int(blc*(np.log10(size_max[i]/blc)+1))
    else:
        size_max[i] = int(blc/(np.log10(blc/size_max[i])+1))

print("after resampling")
print(size_max)
for i in range(nb_class):
    if len(id_toTrain[i]) > size_max[i]:
        id_toTrain[i], tmp = train_test_split(id_toTrain[i], test_size=1-size_max[i]/len(id_toTrain[i]))
    else:
        id_toTrain[i] = np.concatenate((id_toTrain[i], id_toTrain[i][np.random.randint(len(id_toTrain[i]), size=int(size_max[i]-len(id_toTrain[i])))]))
id_toTrain = np.concatenate(id_toTrain)
X_toTrain = X_train[id_toTrain]
Y_toTrain = Y_train[id_toTrain]

before resampling
[12003, 3996]
after resampling
[435, 363]

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.

In [19]:
len(X_toTrain)

798

In [20]:
len(Y_toTrain)

798

In [21]:
len(X_test)

4001

In [22]:
len(Y_test)

4001

In [23]:

# Fitting XGBoost to the Training set
from xgboost import XGBClassifier
classifier = XGBClassifier()
classifier.fit(X_toTrain, Y_toTrain)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [24]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [25]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, y_pred)
cm

array([[2068,  933],
       [ 503,  497]])

In [26]:

print(classifier.score(X_test, Y_test))

0.641089727568108

In [27]:

path_2_test_file = '/content/drive/MyDrive/assignment_new_2020/assignment_new_2020/test.csv'
df_test_full = pd.read_csv(path_2_test_file)

In [28]:
df_test_full.shape

(813818, 332)

In [29]:
import pandas
import random

n = 813818 #number of records in file
s = 81381 #desired sample size
filename = path_2_test_file
skip = sorted(random.sample(range(n),n-s))
df_test1 = pandas.read_csv(filename, skiprows=skip)

In [32]:
df_test1.columns=colnames

In [33]:
df_test1.head()

   day  user_id  item_id  col2    col3  ...  col326  col327  col328  col329  label
0  526  7283313  8228074   0.0  0.3010  ...       0       0       0       0      1
1  526  3448819  8228074   0.0  0.2277  ...       0       0       0       0      1
2  526  1392946  8228074   0.0  0.2794  ...       0       0       0       0      1
3  526  1272439  8228074   0.0  0.0000  ...       0       0       0       0      1
4  526  1464906  8228074   0.0  0.4002  ...       0       0       0       0      1

[5 rows x 332 columns]

In [40]:
df_test1.shape

(81381, 332)

In [41]:
df_test=df_test1.drop(columns=['label','day','item_id','user_id'])
df_test.head()

   col2    col3    col4    col5  col6  ...  col325  col326  col327  col328  col329
0   0.0  0.3010  0.0000  0.0000   0.0  ...       0       0       0       0       0
1   0.0  0.2277  0.0000  0.5885   0.0  ...       0       0       0       0       0
2   0.0  0.2794  0.3526  0.6712   0.0  ...       0       0       0       0       0
3   0.0  0.0000  0.0000  0.2211   0.0  ...       0       0       0       0       0
4   0.0  0.4002  0.0000  0.3595   0.0  ...       0       0       0       0       0

[5 rows x 328 columns]

In [42]:

df_test.head()

   col2    col3    col4    col5  col6  ...  col325  col326  col327  col328  col329
0   0.0  0.3010  0.0000  0.0000   0.0  ...       0       0       0       0       0
1   0.0  0.2277  0.0000  0.5885   0.0  ...       0       0       0       0       0
2   0.0  0.2794  0.3526  0.6712   0.0  ...       0       0       0       0       0
3   0.0  0.0000  0.0000  0.2211   0.0  ...       0       0       0       0       0
4   0.0  0.4002  0.0000  0.3595   0.0  ...       0       0       0       0       0

[5 rows x 328 columns]

In [43]:
df_test.shape

(81381, 328)

In [44]:
X_test[1]

array([0.    , 0.4019, 0.4019, 0.6576, 0.    , 0.1029, 0.    , 0.1029,
       0.163 , 0.    , 0.1029, 0.1029, 0.6743, 0.    , 0.    , 0.    ,
       0.163 , 0.    , 0.    , 0.5547, 0.2057, 0.    , 0.3688, 0.    ,
       0.2389, 0.    , 0.2057, 0.3807, 0.1029, 0.    , 0.3086, 0.1029,
       0.6388, 0.    , 0.    , 0.8011, 0.    , 0.    , 0.2888, 0.1029,
       0.1029, 0.    , 0.    , 0.6593, 0.    , 0.    , 0.    , 0.1029,
       0.7154, 0.3086, 0.    , 0.    , 0.    , 0.2057, 0.3261, 0.4446,
       0.    , 0.163 , 0.    , 0.    , 0.    , 0.    , 0.    , 1.    ,
       0.    , 1.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 1.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.    , 1.    , 0.    , 0.192 , 0.    , 0.192 ,
       0.    , 0.    , 0.    , 0.192 , 0.    , 0.    , 0.    , 0.    ,
       0.6085, 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.3042, 0.    , 0.    , 0.    , 0.    , 0.    , 0.192 , 0.    ,
       0.    , 0.    , 0.    , 0.    , 0.3042, 0.    , 0.    , 0.5389,
       0.    , 0.    , 0.4457, 0.    , 0.    , 0.    , 0.    , 0.4457,
       0.    , 0.    , 0.    , 0.    , 0.4457, 0.192 , 0.    , 0.    ,
       0.    , 0.    , 0.192 , 0.    , 0.    , 0.    , 0.    , 0.    ,
       1.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 1.    , 0.    , 0.    , 0.    , 0.    , 0.    ])

In [45]:

a=df_test.to_numpy()

In [46]:
prediction = pd.DataFrame(classifier.predict_proba(a), columns=['Prob_0','Prob_1'])

In [47]:

df_test1['Prob_0'] = prediction['Prob_0']
df_test1['Prob_1'] = prediction['Prob_1']

In [48]:
conditions=[(df_test1['Prob_0']> 0.5 ),
            (df_test1['Prob_0']<= 0.5 )]

In [49]:
choices=[-1,1]
df_test1['Pred']=np.select(conditions,choices,default='null')
df_test1['Pred']=pd.to_numeric(df_test1['Pred'])

In [50]:
df_test1

       day  user_id  item_id  col2  ...  label    Prob_0    Prob_1  Pred
0      526  7283313  8228074   0.0  ...      1  0.396821  0.603179     1
1      526  3448819  8228074   0.0  ...      1  0.369528  0.630472     1
2      526  1392946  8228074   0.0  ...      1  0.328337  0.671663     1
3      526  1272439  8228074   0.0  ...      1  0.333985  0.666015     1
4      526  1464906  8228074   0.0  ...      1  0.405385  0.594615     1
...    ...      ...      ...   ...  ...    ...       ...       ...   ...
81376  537   136740  8358653   0.0  ...      0  0.196193  0.803807     1
81377  537   136740  6765690   0.0  ...      0  0.490184  0.509816     1
81378  537   367828  8358644   0.0  ...      0  0.086409  0.913591     1
81379  537   446488   109629   0.0  ...      0  0.837831  0.162169    -1
81380  537  2243334  8346526   0.0  ...      0  0.384364  0.615636     1

[81381 rows x 335 columns]

In [51]:

cm_test=confusion_matrix(df_test1['label'],df_test1['Pred'])

In [52]:
cm_test

array([[    0,     0,     0],
       [32052,     0, 30016],
       [ 8541,     0, 10772]])

In [53]:
32052+10772

42824

In [54]:
42824+8541+30016

81381

In [56]:
42824/81381

0.5262161929688748